### ISSUE TITLE
[feature request] option to disable and/or customization of sizing when pushing the file content when TOC is pinned / unpinned

### ISSUE THREAD

**Issue by sisi-sh** [PKM-er/obsidian-floating-toc-plugin#100]
Love the plugin! Lowkey didn't find it all that useful in general though and a little obtrusive on mobile. ended up disabling it via CSS. A style setting would be great!

Thanks for the hard work! 

Snippet for anyone browsing:
```css
.workspace-leaf-content .floating-toc-div.pin:is(.floating-left,.floating-both)+.markdown-source-view>.cm-editor,
.workspace-leaf-content .floating-toc-div:is(.floating-left,.floating-both)+.markdown-source-view>.cm-editor {
    padding-left: inherit !important;
}
```
