### ISSUE TITLE
启用插件后阅读视图下内嵌文档样式异常

### ISSUE THREAD

**Issue by qwqw3qee** [PKM-er/obsidian-floating-toc-plugin#113]
未启用插件时，含有内嵌文档的笔记在阅读视图下的显示如下：
![image](https://github.com/user-attachments/assets/ae51edb1-fba3-4f2f-9460-9e83fb739e48)
启用插件后，内嵌文档左侧边距异常
![image](https://github.com/user-attachments/assets/5a0174fb-6b00-4565-a081-a8d05c1a117b)

我尝试在`style.css`中，修改第652行代码，将`.markdown-preview-view`去掉，并将`padding-left`的值改为2rem后显示正常了（仅针对大纲在左侧的情况，其他情况没进行修改），修改后样式代码如下：
```css
.workspace-leaf-content .floating-toc-div:is(.floating-left,.floating-both)~.markdown-reading-view {
  padding-left: 2rem;
}
```
