### ISSUE TITLE
大纲显示效果受到sheet plus插件的影响

### ISSUE THREAD

**Issue by qwqw3qee** [PKM-er/obsidian-floating-toc-plugin#114]
启用sheet plus插件后，大纲的toolbar的位置会发生变化。
启用sheet plus插件前：
![image](https://github.com/user-attachments/assets/7bc08634-0987-4578-a6d8-8c6fffd8df7c)
启用sheet plus插件后：
![image](https://github.com/user-attachments/assets/4b43c003-c858-464d-ac2e-a9360bcfe7b9)
原本觉得是sheet plus插件的问题，在该插件项目下提的issue，[#38](https://github.com/ljcoder2015/obsidian-sheet-plus/issues/38#issue-2518628899)，然后我尝试了下修改css样式，发现将top换成margin-top可以避免heet plus插件的影响，具体css代码如下：
```css
.floating-toc-div .toolbar
{
  display: list-item;
  opacity: 0.8;
  z-index: 2;
  background: var(--floating-toc-background-color);
  position: fixed;
  margin-top: -28px;
  margin-left: 10px;
}
```
(将原本的`top: 75px;`改为`margin-top: -28px;`)
这样不管是否启用sheet plus插件，大纲的显示效果都会保持一致。
