### ISSUE TITLE
建议新增一个排除指定目录生成toc的选项

### ISSUE THREAD

**Issue by CAI2H** [PKM-er/obsidian-floating-toc-plugin#83]
由于部分仓库会有一个homepage的页面，这个页面也存在标题，此时生成toc会影响美观。
![image](https://github.com/PKM-er/obsidian-floating-toc-plugin/assets/26704507/449b3195-9293-478c-b9ac-88ca212ac5da)

**Comment by cumany** [comment]
应该 还是用的我之前做的 Blue topaz example  示例库，其实用一个css片段就可以解决。
```css
 .workspace-leaf .floating-toc-div:has(+ .markdown-source-view.myhome) {
  display: none;
}
```

这样 如果homepage 的yaml区域设置了一个 cssclass myhome  就可以生效。（示例库默认设置的有）
